{% set version = "3.5.0" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: 1b095c42dc91d426f3ae85101796b14d265887f8f36f3aad143a5f29effdc39d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  license_file: license.txt
  summary: 'Tools for using a Web Server Gateway Interface stack'
  description: |
    Paste provides several pieces of "middleware" (or filters) that can be
    nested to build web applications. Each piece of middleware uses the WSGI
    (PEP 333) interface, and should be compatible with other middleware based
    on those interfaces.
  doc_url: https://paste.readthedocs.io/en/latest/
  doc_source_url: https://bitbucket.org/ianb/paste/src/default/docs/index.txt
  dev_url: https://bitbucket.org/ianb/paste

extra:
  recipe-maintainers:
    - kwilcox
    - daf
