{% set name = "paste" %}
{% set version = "2.0.3" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/ianb/paste/get/{{ version }}.tar.gz
  sha256: d6b1ac1223c42d0a8de5e5fa46b142bff688d4f535738a0ba938d9b0a78533dd

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.4.0

  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  summary: 'Tools for using a Web Server Gateway Interface stack'
  description: |
    Paste provides several pieces of "middleware" (or filters) that can be
    nested to build web applications. Each piece of middleware uses the WSGI
    (PEP 333) interface, and should be compatible with other middleware based
    on those interfaces.
  doc_url: https://paste.readthedocs.io/en/latest/
  doc_source_url: https://bitbucket.org/ianb/paste/src/default/docs/index.txt
  dev_url: https://bitbucket.org/ianb/paste

extra:
  recipe-maintainers:
    - kwilcox
    - daf
