{% set version = "3.4.6" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: 001370f4fcc7446006b52a39ed386341fce626605af711e0ec18ddb0b4912cb7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  license_file: license.txt
  summary: 'Tools for using a Web Server Gateway Interface stack'
  description: |
    Paste provides several pieces of "middleware" (or filters) that can be
    nested to build web applications. Each piece of middleware uses the WSGI
    (PEP 333) interface, and should be compatible with other middleware based
    on those interfaces.
  doc_url: https://paste.readthedocs.io/en/latest/
  doc_source_url: https://bitbucket.org/ianb/paste/src/default/docs/index.txt
  dev_url: https://bitbucket.org/ianb/paste

extra:
  recipe-maintainers:
    - kwilcox
    - daf
