{% set version = "3.0.2" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/paste/Paste-{{ version }}.tar.gz
  sha256: d64c65d7779a57b426c7d4112816310f6d92ab4f038990a7c877743180dac000

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - six >=1.4.0

  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  summary: 'Tools for using a Web Server Gateway Interface stack'
  description: |
    Paste provides several pieces of "middleware" (or filters) that can be
    nested to build web applications. Each piece of middleware uses the WSGI
    (PEP 333) interface, and should be compatible with other middleware based
    on those interfaces.
  doc_url: https://paste.readthedocs.io/en/latest/
  doc_source_url: https://bitbucket.org/ianb/paste/src/default/docs/index.txt
  dev_url: https://bitbucket.org/ianb/paste

extra:
  recipe-maintainers:
    - kwilcox
    - daf
