# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "g2fvhKm0gD0mLe7IlBaxJV9piKPWitS2oFgYFSLoOPuyx+rM0jrKE5sPowQRNxN0hmkN27sQk/ZeQcUyBpLmfyucXi8Of5Ur3hi12U25VJzQkicItybKbFk8k68XPskmsT5Bwi0kg5UKOMRPb5/fiAOd2NlaPddq3sasaPBmgRRVh4Q+4ZVK07ChED10DoPDBKXk3eSoJ5N/Yms5y4WxRUWC8xgh/1GpgbymjpU4cqnUwsVvPBkj5Se97SWVfw8NLEERUiN2/duxTGXBIOUQgimgm3kHozKi7rdNp9i4Ce30uPm0aRMKEpfAf/tilKFYNvnB0jM8XXltkRJ3rV+DTj+aEzPh8NB5I8blmToIR8G02YgTgaSTG/NlWLLNeFzCyfdPOsvZNTFJK1FYnoho5U+Zs+zw0EPapJrQ5uqP/VtlEaCVskB1kM0IJiv1ptL9jhve3rbDB0uji0v5mwGRWSrL9GVDyB7+codL+6lsP3CPAbFWKuy4pAOgzUP9MHS4c/uUN2w7FLTe0yDFrvAY2DJVLlrHCs0Jzjax+JTm01QFoFc5YXIknUdLkDm9TURfXgwc6ZWyNQ01YnsjnjCqvx08mQlVZ11+WTmLE1MrCGZtmlx7Hx4527ayAMDJZUpqLAN0NqtPU0Vye0Gu73etfMk/Bg4XrGeYYlrgP1F6ANk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml