travis:
  secure:
    BINSTAR_TOKEN: gA8TsfeJqb5oCnbp3uRd/m85yoa+plu5WEOcl0Y7us7Fc87kcP1QGZ7LH7kJaIdPizIDdNJleCrbJ5diNqST6ytTXD2ykgp65a/Asvnmzu6deriI9du3EyvaAlMltKMZbAZY1+RVlETd2vGvhV0ck0SZgtc6NiQ091CY+4y4c+3I2DGemVTJnLcq15q/42qGu6qEsl/BShZFffQ9ZIY7MOXIjfQnelWiHqS3p0r76eEavL0Qt2ZTJ82w3idQOV81aHRBdZGsTI68lpIvbUOqkFPVBjLZumQkFEatB1DNbjdJp+rmoQ/GyG3Nt/lA65uc834aqcRwXyh3qYwHggBlpzA6qp4cTVhy9DPG9XlnkFa0LQoDWngMQ2XTshYe0yGefwF6Rk/1Cil/O6vMhv247gm6tUdD+5fmS7QIzuhVIQ2ws1FBQ8cewp6KLw5o7wa4ZuJYpJuBMrl/9nk8dpLLbJdAojBtV9CbGiAztt2+/ZTZxle6oDCoLRwPe+dzG6QcUByLXmG7RdOJfovngjgljKWk0RR/8Wqjdst17d26KaYBZKiEvNG1KJET5US/IDc3HdH2spm/xRkptI6QFiOsGuWiIqu575hE+dXBGBrvO+9UmcJ0P4nTDYyuPOM5l/Zf4HFOB/+DkKkLl0yOJm3H+Ei3qW2J+mRqTPv5HqRkn1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
