travis:
  secure:
    BINSTAR_TOKEN: GqDtEIpbqnexjyYFWsRRZcY3331poQqbDtuWpEw3LmjiKd+HnhqoIoDLEd9EGuAVSJTzfCqlFYfmFY8/fqfWfCqzMi3qQE71S6Z3Wbmf+oM0wSuqt5vkW2Jgi4g1OjIEAh276veCXaKzk1w+NPOVv0u0Y6rbHOudpM3tEQUjacdraylukfoCgz3hiEPPTtZAojPo8d/zNB0SaDzdD148ovMD8+sUZzFdDIk7tsQoOS7nF/ThjhAIKjksrcu6de36KMxz6CK6xs0fdROry78ZyPYbbJpZbFRU6pspEFPBeNHr2g26GaaIfyfWvqmmwuUxLLiaZkerlZTQOG2x9Op2my+2evq8WCI4H2v0YviJZeJU0n96E6v6/ozouLvvVJGOZg87Jom0CSKnPTXnPWDgtO78z1YrHxJ2uBboEbuydJqUdg3otZ4yhAFZqVx72o50CnteNqNIl6Fn06AQ8mmTwm7rT16se5H5W0djHDtDwn4SvkVcvb0BPIgdt8kIFScayP7/v0SPaTjlfdfhQnqBEbP8VWSmPashxYLQ0//7ijU+RL3cR7a/K5c23rsbgawcLhglHGWRkyLkkuAHGL+SndSUqZBF8+3hIbDLsq7F94QifXsVB5rprdBdM2kOtM7z9f5iuoMZomY867rgbLgJwna73t5o4EzQlQ6tyyKVy4E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
